### ISSUE TITLE
tar1090 with enable_978, no wget installed

### ISSUE THREAD

**Issue by ww2air** [mikenye/docker-tar1090#34]
Enabling 978 and pointing url to skyaware978 looks like it grabs json using wget. Which is not installed in container. Install wget fixes issue. 

[tar1090] /usr/local/share/tar1090/tar1090.sh: line 209: wget: command not found

**Comment by mikenye** [comment]
Thanks for letting me know. We don't have UAT in Australia so I haven't been able to test this. I've added `wget` to the image. Can you pull the new version and test? Thanks.

**Comment by ww2air** [comment]
Pulled and working fine. Thanks for the update.

**Comment by mikenye** [comment]
Thanks for testing! Happy new year.
