### ISSUE TITLE
Missing Type Code and Picture in latest Safari on OS X

### ISSUE THREAD

**Issue by rice3253** [mikenye/docker-tar1090#48]
Hello,

The type code and picture are missing on Safari on OS X, a Chrome browser on the same machine shows the type code and picture. Chrome, Safari, and OS X have all been updated to the latest versions.

**Comment by rice3253** [comment]
I am noticing I am getting the following console message spammed that is not present in Chrome: a3a0ed: Database load error: parsererror at URL: db-1620696395/A.js
planeObject_1620696395.js:2084

The a3a0ed is the Hex ID of the aircraft, and varies with each error message in the JavaScript Console log

**Comment by wiedehopf** [comment]
Probably fixed by: https://github.com/wiedehopf/tar1090/commit/cc1b1b07f57679cd81cffa7c5fe728738fadc971

**Comment by mikenye** [comment]
I’ve triggered a build: https://github.com/mikenye/docker-tar1090/actions/runs/938446029

**Comment by mikenye** [comment]
Thanks @wiedehopf

**Comment by fredclausen** [comment]
Confirmed fixed on my end

**Comment by mikenye** [comment]
Thanks Fred!

**Comment by rice3253** [comment]
I can confirm this. Thank you so much :)
